experiment:
  name: PL_BCNN 1_1
  log_dir: results/PeerLearning
  cuda: [0]
  seed: 0
dataset:
  name: web_bird
  root_dir: data/web-bird
  meta_dir: metadata/web_bird
  batch_size: 8
  num_workers: 0
  transformer:
    image_size: 224
    resize_size: 256
model:
  name: PeerLearningNet
  base_model:         # PeerLearningNet contains two identical models. Here it uses a BilinearCNN.
    name: BCNN
    stage: 2
    num_classes: 200
  drop_rate: 0.35     # The maximum drop rate, `\xi` in Eqn.(2).
  T_k: 10             # The number of epochs after which d(T) is no longer updated, `T_k` in Eqn.(2).
  load: results/PeerLearning/PL_BCNN 1/best_model.pth
train:
  epoch: 200
  save_frequence: 50
  val_first: True
  optimizer:
    name: Adam
    lr: 0.00001
    weight_decay: 0.00001
    momentum: 0.9
  scheduler:
    name: ''
    T_max: 200
    warmup_epochs: 10
    lr_warmup_decay: 0.01
  criterion:
    name: peer_learning_loss
